### ISSUE TITLE
Add option to make available all source repositories for the specified product in `repose-install`

### ISSUE THREAD

**Issue by viccuad** [openSUSE/repose#3]
Hi,

Currently, source packages cannot be easily accessed on hosts.

Ideally, all source packages should be present for all products and all hosts,
and a repose flag for enabling the right channels/installing the right DVDs when
installing a product seems the way to go.

Cheers.

**Comment by roman-neuhauser** [comment]
this is already possible.

if you have the repositories defined in repoq.rules, you can have them added by using explicit repository patterns, either positive:

    repose install host... -- sles:12.1::gm,up,dg,du

or negative:

    repose install host... -- sles:12.1::~.

the former should be obvious, the latter too (it's all documented in repose(1) and repoq(1)), but i'll rehash it here: a `REPA` with negated *T* part asks for all tags except those given, and since no url is tagged `.` in `repoq.rules`, you'll get everything.

**Comment by plusky** [comment]
All logic moved to refhosts.yml - no a repose issue anymore
